version: "2"

services:

  bedrock:
    volumes:
      - .certs:/etc/nginx/certs
    volumes_from:
      - container:PROJECT_NAME-sync:rw # will be mounted on /var/www
    env_file:
      - .docker/stages/dev/env/db.development.env
      - .docker/stages/dev/env/bedrock.development.env

  db:
    env_file: .docker/stages/dev/env/db.development.env

  phpmyadmin:
    env_file: .docker/stages/dev/env/db.development.env

volumes:
  PROJECT_NAME-sync:
    external: true