options:
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose.development.yml'
  verbose: true
syncs:
  PROJECT_NAME-app-sync:
    src: './bedrock'
    dest: '/var/www'
    sync_strategy: 'unison'
    sync_excludes_type: 'Name'
    sync_user: 'www-data'
    sync_userid: '33'
    notify_terminal: true
    sync_host_ip: '127.0.0.1'
    sync_host_port: 20872

    sync_excludes: ['.DS_Store', '.sass-cache/*', 'sass-cache/*', 'bower_components*', 'node_modules*', 'jspm_packages*', '.git/*', '._*']

  PROJECT_NAME-templates-sync:
    src: './templates'
    dest: '/var/templates'
    sync_strategy: 'unison'
    sync_excludes_type: 'Name'
    sync_user: 'www-data'
    sync_userid: '33'
    notify_terminal: true
    sync_host_ip: '127.0.0.1'
    sync_host_port: 20873

    sync_excludes: ['.DS_Store', '.sass-cache/*', 'sass-cache/*', 'bower_components*', 'node_modules*', 'jspm_packages*', '.git/*', '._*']